# Model configuration
# configs/model/pix2struct_large.yaml

model_name: "google/pix2struct-large"
max_length: 1024  # Increased for longer HTML/CSS sequences
image_size: [512, 512]

# Model-specific parameters
max_patches: 512
vocab_size: 50244

# Generation parameters
generation:
  max_length: 1024
  num_beams: 5
  early_stopping: true
  do_sample: false
  temperature: 1.0